[pytest]  # Секция настроек pytest
minversion = 7.0 
addopts = -v -s --tb=short --strict-markers  
# addopts - дополнительные параметры запуска
# -v (verbose) - подробный вывод
# -s - показывать print в консоли (не перехватывать вывод)
# --tb=short - короткий формат traceback (меньше текста при ошибке)
# --strict-markers - требовать регистрации всех маркеров (если маркер не объявлен - ошибка)

markers =  # Список маркеров
    smoke: Маркер для smoke-тестов  # smoke - быстрые тесты для проверки критического функционала
    regression: Маркер для регрессионных тестов  # regression - полный набор тестов
    slow: Тесты, которые выполняются долго  # slow - долгие тесты (можно исключать при быстром прогоне)
    db: Проверки базы данных
pythonpath = .
testpaths = tests  # Папка, где pytest ищет тесты (может быть несколько через пробел)
python_files = test_*.py  # Шаблон имен файлов с тестами
python_classes = Test*  # Шаблон имен классов с тестами (для unittest стиля)
python_functions = test_*  # Шаблон имен функций с тестами